# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4eba3cb5b022b694079c2ca4892392f1f365a378f354874e7890fcd637337c3a780e6a1c6b59e0e45b904a97a018f8fae3ff7a2e3189822161c7b8e7afe59435

test:
  secret_key_base: 6411d352fb6b9bf7d8b385f1c4f2a2f3062a86e33bcc99c818df7bbd957409372d899098889dfb0f94aef8b2f23a050f03dbf96f777dda90895caffb9744f0de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 4eba3cb5b022b694079c2ca4892392f1f365a378f354874e7890fcd637337c3a780e6a1c6b59e0e45b904a97a018f8fae3ff7a2e3189822161c7b8e7afe59435
